#!/usr/bin/env python3
"""
Convert PNG sprite sheets to U8g2-compatible XBM C headers.

Usage:
    python3 tools/png_to_sprite.py src/sprites/egg/egg.png
    python3 tools/png_to_sprite.py src/sprites/**/*.png
    python3 tools/png_to_sprite.py egg.png --frames 4      # horizontal sprite sheet
    python3 tools/png_to_sprite.py egg.png --out include/sprites/egg.h

Each output .h file contains a PROGMEM uint8_t array per frame, plus
width/height/count defines. Use with u8g2.drawXBMP().

Pixel rules:
  - Transparent (alpha < 128) → off (0)
  - Any other colour            → on  (1)  [white/light pixels = off if --invert]
"""

import argparse
import sys
from pathlib import Path
from PIL import Image


def image_to_xbm_bytes(img: Image.Image) -> list[int]:
    """Convert a 1-bit image to XBM byte list (LSB-first, rows padded to bytes)."""
    w, h = img.size
    row_bytes = (w + 7) // 8
    data = []
    pixels = img.load()
    for y in range(h):
        for byte_x in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                if x < w and pixels[x, y]:
                    byte |= (1 << bit)   # XBM is LSB-first
            data.append(byte)
    return data


def png_to_1bit(img: Image.Image, invert: bool, threshold: int) -> Image.Image:
    """Flatten RGBA/RGB image to 1-bit using alpha + luminance threshold."""
    img = img.convert("RGBA")
    mono = Image.new("1", img.size, 0)
    src = img.load()
    dst = mono.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = src[x, y]
            if a < 128:
                pixel = 0   # transparent = off
            else:
                lum = int(0.299 * r + 0.587 * g + 0.114 * b)
                pixel = 1 if lum < threshold else 0
            dst[x, y] = pixel ^ invert
    return mono


def split_frames(img: Image.Image, frame_w: int, frame_h: int) -> list[Image.Image]:
    """Slice a horizontal sprite sheet into individual frames."""
    frames = []
    for x in range(0, img.width, frame_w):
        frames.append(img.crop((x, 0, x + frame_w, frame_h)))
    return frames


def sanitize_name(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s).lower()


def generate_header(
    name: str,
    frames: list[list[int]],
    frame_w: int,
    frame_h: int,
) -> str:
    guard = f"SPRITES_{name.upper()}_H"
    lines = [
        f"#pragma once",
        f"// Auto-generated by tools/png_to_sprite.py — do not edit",
        f"#include <pgmspace.h>",
        f"",
        f"#define {name.upper()}_WIDTH  {frame_w}",
        f"#define {name.upper()}_HEIGHT {frame_h}",
        f"#define {name.upper()}_FRAMES {len(frames)}",
        f"",
    ]

    frame_names = []
    for i, data in enumerate(frames):
        fname = f"{name}_f{i}"
        frame_names.append(fname)
        hex_vals = ", ".join(f"0x{b:02x}" for b in data)
        lines.append(
            f"static const uint8_t {fname}[] PROGMEM = {{ {hex_vals} }};"
        )

    lines += [
        f"",
        f"static const uint8_t* const {name}_frames[{name.upper()}_FRAMES] PROGMEM = {{",
        "    " + ", ".join(frame_names),
        f"}};",
        f"",
    ]
    return "\n".join(lines)


def convert(
    src: Path,
    out: Path | None,
    num_frames: int,
    invert: bool,
    threshold: int,
    verbose: bool,
):
    img = Image.open(src)
    name = sanitize_name(src.stem)

    if num_frames > 1:
        frame_w = img.width // num_frames
        frame_h = img.height
        raw_frames = split_frames(img, frame_w, frame_h)
    else:
        frame_w, frame_h = img.size
        raw_frames = [img]

    xbm_frames = []
    for i, frame in enumerate(raw_frames):
        mono = png_to_1bit(frame, invert, threshold)
        xbm_frames.append(image_to_xbm_bytes(mono))
        if verbose:
            print(f"  frame {i}: {frame_w}x{frame_h} → {len(xbm_frames[-1])} bytes")

    header = generate_header(name, xbm_frames, frame_w, frame_h)

    if out is None:
        out = src.with_suffix(".h")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header)
    print(f"{src} → {out}  ({len(raw_frames)} frame(s), {frame_w}x{frame_h})")


def main():
    parser = argparse.ArgumentParser(description="PNG → U8g2 XBM sprite header")
    parser.add_argument("images", nargs="+", type=Path, help="PNG file(s) to convert")
    parser.add_argument("--frames", type=int, default=1,
                        help="Number of frames in a horizontal sprite sheet (default 1)")
    parser.add_argument("--out", type=Path, default=None,
                        help="Output .h path (default: same location as PNG)")
    parser.add_argument("--invert", action="store_true",
                        help="Invert: treat light pixels as on, dark as off")
    parser.add_argument("--threshold", type=int, default=128,
                        help="Luminance threshold 0-255, below = on (default 128)")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    for src in args.images:
        if not src.exists():
            print(f"ERROR: {src} not found", file=sys.stderr)
            sys.exit(1)
        convert(src, args.out, args.frames, args.invert, args.threshold, args.verbose)


if __name__ == "__main__":
    main()
