#pragma once
// Auto-generated by tools/png_to_sprite.py — do not edit
#include <pgmspace.h>

#define HAPPINESS_WIDTH  7
#define HAPPINESS_HEIGHT 7
#define HAPPINESS_FRAMES 3

static const uint8_t happiness_f0[] PROGMEM = { 0x00, 0x22, 0x00, 0x00, 0x41, 0x41, 0x3e }; // Happy
static const uint8_t happiness_f1[] PROGMEM = { 0x00, 0x22, 0x00, 0x00, 0x3e, 0x00, 0x00 }; // Medium
static const uint8_t happiness_f2[] PROGMEM = { 0x00, 0x22, 0x00, 0x00, 0x1c, 0x22, 0x41 }; // Sad

static const uint8_t* const happiness_frames[HAPPINESS_FRAMES] PROGMEM = {
    happiness_f0, happiness_f1, happiness_f2
};
